a1 = input()
a2 = input()
a3 = input()
a4 = input()
a5 = input()

print(f"The type of a1 is {type(a1)} and value of a1 is {a1}")
print(f"The type of a2 is {type(a2)} and value of a1 is {a2}")
print("The type of a3 is {} and value of a3 is {}".format(type(a3), a3))
print("The type of a4 is {} and value of a4 is {}".format(type(a4), a4))
print("The type of a5 is {} and value of a5 is {}".format(type(a5), a5))
